#! /bin/sh

bspc config border_width     1
bspc config window_gap       0
bspc config top_padding      15 
bspc config split_ratio      0.50

bspc config borderless_monocle true
bspc config gapless_monocle    true
bspc config focus_by_distance  true
bspc config focused_border_color "#eac117"
bspc config urgent_border_color "#38acec"

bspc monitor -d I II III

sxhkd &
xcompmgr &
kill wpa_supplicant
pulseaudio &
feh --bg-scale /home/rndmprsn/Pictures/arturodonate_skyline.jpg
xsetroot -cursor_name left_ptr
~/Code/bar/bar.sh &
